services:
  Modules.Policy.PolicyRepository:
    class: ../../../../modules/policy/infrastructure/MongoPolicyRepository
    arguments: ["@Shared.ConnectionManager"]

  Modules.Policy.PoliciesFinder:
    class: ../../../../modules/policy/application/PoliciesFinder
    arguments: ["@Modules.Policy.PolicyRepository"]

  Modules.Policy.PolicyCreator:
    class: ../../../../modules/policy/application/PolicyCreator
    arguments: ["@Modules.Policy.PolicyRepository"]
