services:
  Modules.Policy.PolicyRepository:
    class: ../../../../modules/policy/infra/MongoPolicyRepository
    arguments: ["@Shared.ConnectionManager"]

  Modules.Policy.PoliciesFinder:
    class: ../../../../modules/policy/useCases/PoliciesFinder
    arguments: ["@Modules.Policy.PolicyRepository"]

  Modules.Policy.PolicyCreator:
    class: ../../../../modules/policy/useCases/PolicyCreator
    arguments: ["@Modules.Policy.PolicyRepository"]
