services:
  shared.MongoConfig:
    factory:
      class: ../../../../modules/policy/shared/persistence/mongo/MongoConfigFactory
      method: 'createConfig'

  Shared.Logger:
    class: ../../../../shared/infra/WinstonLogger
    arguments: []

  Shared.ConnectionManager:
    factory:
      class: ../../../../shared/infra/persistence/mongo/MongoClientFactory
      method: 'createClient'
    arguments: [ 'policy', '@shared.MongoConfig' ]
