services:
  shared.MongoConfig:
    factory:
      class: ../../../../modules/policy/shared/persistence/mongo/MongoConfigFactory
      method: 'createConfig'

  Shared.Logger:
    class: ../../../../shared/infrastructure/WinstonLogger
    arguments: []

  Shared.ConnectionManager:
    factory:
      class: ../../../../shared/infrastructure/persistence/mongo/MongoClientFactory
      method: 'createClient'
    arguments: [ 'policy', '@shared.MongoConfig' ]

  Shared.EventBus:
    class: ../../../../shared/infrastructure/EventBus/InMemory/InMemoryAsyncEventBus
    arguments: []
