services:
  Apps.policy.controllers.PoliciesGetController:
    class: ../../controllers/PoliciesGetController
    arguments: ["@Modules.Policy.PoliciesFinder"]

  Apps.policy.controllers.PolicyPostController:
    class: ../../controllers/PolicyPostController
    arguments: ["@Modules.Policy.PolicyCreator"]

  Apps.policy.controllers.StatusGetController:
    class: ../../controllers/StatusGetController
    arguments: []
